# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Synopsys Detect action 3.0 intelligent scan  
      uses: synopsys-sig/detect-action@v0.3.0
       # env:
        # NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
      with:
        scan-mode: INTELLIGENT # RAPID is the default value - can be excluded 
#        scan-mode: RAPID # Can be omitted, since this is the default value
        github-token: ${{ secrets.GITHUB_TOKEN }}
        detect-version: 7.9.0
        blackduck-url: ${{ secrets.TEST_BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.TEST_BLACKDUCK_API_TOKEN }}
    

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
